### ISSUE TITLE
add c3lang in exercism

### ISSUE THREAD

**Issue by codehangen** [exercism/generic-track#139]
**What programming language should we add?**
c3lang

**What is the official website for the language?**
https://www.c3-lang.org/

**Is this a language that comes in many variants? If so, which variant should we support?**
No.

**Does the language have an official logo?** If so

- please include a link to an example
https://avatars.githubusercontent.com/u/53541653?s=200&v=4

- please list the attribution rights of that logo
https://github.com/c3lang/

**Does the language have an unofficial logo?** If so

- please explain the ways in which people use the unofficial logo
Am not aware of an unofficial logo

- please include a link to an example
none.

- please list the attribution rights of that logo
none.

**Is there a testing framework available for the language?**
No.

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?** If so

- what is Highlightjs' canonical spelling for the language?
It is not officially supported, likely because this language is still relatively new.

- what file extensions should be highlighted?
  ``.c3``

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**
It is not officially supported, likely because this language is still relatively new. But... It is very similar syntactically to C. See this [c3lang/c3docs](https://github.com/c3lang/c3docs)

**Who will be leading the effort to launch the track?**
Maybe c3lang community.

**Comment by kytrinyx** [comment]
It looks interesting.

Once we have at least one person (preferably two or three) who are willing to take the lead on implementing a c3 track on Exercism we can bootstrap a repository for it.

**Comment by kytrinyx** [comment]
Creating a track on Exercism is a big effort and has quite a few moving pieces. I can't tell from this issue whether you'd like to take on that work, or whether you've opened the issue to indicate that you wish that a c3 track would exist, and that you hope that someone else would be willing to take on that work.

**Comment by kytrinyx** [comment]
@codehangen Absolutely! We have a whole bunch of exercises that you can adapt. Shall I make the repo for you?

**Comment by kytrinyx** [comment]
@codehangen That's exciting! I've made you a repo here: https://github.com/exercism/c3lang/issues/1 You should have an invite to the team that has write access to the repo. If you don't see it, holler and I'll troubleshoot.

If you have other people who are helping build it let me know and I'll add them to the team as well.

Lastly, ask whatever questions you can think of in the Building Exercism section of the forum (https://forum.exercism.org/c/exercism/building-exercism/125), as there are a bunch of knowledgable and helpful folks there.

Thanks for taking this on, I'm looking forward to seeing how the track develops.
