### ISSUE TITLE
Rexx Language Track

### ISSUE THREAD

**Issue by kotp** [exercism/generic-track#148]
**What programming language should we add?**
Rexx

**What is the official website for the language?**

**Is this a language that comes in many variants? If so, which variant should we support?**

To be discovered.  Here are some flavors to download.

- [Download ooRexx](https://sourceforge.net/projects/oorexx/files/)
- [Download Regina](https://sourceforge.net/projects/regina-rexx/files/)
- [Download NetRexx](http://www.netrexx.org/downloads.nsp)
- [Download BSF4ooRexx](https://sourceforge.net/projects/bsf4oorexx/files/)

**Does the language have an official logo?**

**Does the language have an unofficial logo?**

None found, or too many found, but color red, Rexx should work.

However, there are [logos] for the four flavors indicated above.

[logos]: https://www.rexxla.org/products.srsp

**Is there a testing framework available for the language?**

To be discovered.

**Is this language listed as 'supported' by [Highlightjs]([https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)?**

No.

**If it is not supported by Highlightjs, what is the closest supported language it maps to?**

To be discovered.

**Who will be leading the effort to launch the track?**

To be discovered.

Monitor the discussion in [the forum]

[the forum]: http://forum.exercism.org/t/starting-a-rexx-track/730

**Comment by ajborla** [comment]
I have been participating in the Exercism forum thread on starting a REXX track, and would like to be its maintainer. Not sure how best to make this request so am  doing so here.

REXX and git I already know, but need to get up to speed with the pragmatics of managing an Exercism track on github. So, what's the best way to proceed ?

**Comment by kotp** [comment]
Once the new track repository is approved and created, the @exercism/maintainers-admin team  can set that up.  I think you have already stated your desire to help in the [discussion] about this. 

[discussion]: https://forum.exercism.org/t/starting-a-rexx-track/730/22

**Comment by iHiD** [comment]
@kytrinyx: @ajborla is volunteering to be the maintainer for this track. So could you go ahead and bootstrap pls. (cc @jonathandmiddleton and @ErikSchierboom too)

**Comment by ajborla** [comment]
Thank you - very much look forward to the challenge !

**Comment by kytrinyx** [comment]
Yay, that is great news! I will bootstrap this as soon as I get back to my computer.

**Comment by kytrinyx** [comment]
Here you go @ajborla https://github.com/exercism/rexx/issues/1

You should have an invite to the `exercism/rexx` team that has write-access to the repo.
If there are others who want to build the track with you let me know and I'll add them to the team as well.

**Comment by ajborla** [comment]
Thank you !

**Comment by ErikSchierboom** [comment]
@ajborla I've added you as a maintainer to the DB. This will come in useful once we're ready to test the track .

**Comment by ajborla** [comment]
@ErikSchierboom Thank you.
